# Generated by Django 5.1.7 on 2025-04-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_customuser_is_admin_srq20resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
